Repository usdot-jpo-ode/ode-output-validator-library, pull requests merged in 2019-04, with the labels that each got.

#9 ODE-1243 Improve documentation
  README.md
Labels: documentation

#10 Librarization
  odevalidator/result.py
  odevalidator/sequential.py
  setup.py
Labels: bug

#11 Assert config file exists to prevent empty validations errors
  odevalidator/__init__.py
Labels: bug

#13 Initialize module imports using init script to remove namespace requirement
  odevalidator/__init__.py
  odevalidator/sequential.py
  odevalidator/validator.py
Labels: enhancement

#12 Corrected packaging
  .gitignore
  install.sh
  odevalidator/__init__.py
  odevalidator/sequential.py
  odevalidator/validator.py
  setup.py
  test.sh
Labels: bugfix

#14 Add name to sequential check field
  odevalidator/validator.py
Labels: enhancement

#15 ODE-1234 Conditional matching to support optional fields and multi-record type processing
  README.md
  install.sh
  odevalidator/config.ini
  odevalidator/result.py
  odevalidator/sequential.py
  odevalidator/validator.py
  samples/bsmTxBad.json
  samples/bsmTxGood.json
  setup.py
  test/bad.json
  test/good.json
Labels: enhancement

#16 Configuration Improvements
  install.sh
  odevalidator/__main__.py
  odevalidator/sequential.py
  odevalidator/validator.py
  setup.py
Labels: enhancement

#20 ODE-1234 cleanup
  .gitignore
  odevalidator/__main__.py
  odevalidator/validator.py
  setup.py
  test.sh
Labels: cleanup

#22 ODE-1268 Validation Library Enhancements
  README.md
  install.sh
  odevalidator/config.ini
  odevalidator/validator.py
  requirements.txt
  setup.py
  test.sh
  tests/__init__.py
  tests/testfiles/bad.json
  tests/testfiles/good.json
  tests/unit_test.py
  unittest.sh
Labels: documentation, enhancement

#23 Add Travis file for CI
  .gitignore
  .travis.yml
Labels: enhancement

#24 ODE-1262 Preliminary Integration & Unit Tests
  .gitignore
  odevalidator/__main__.py
  odevalidator/result.py
  odevalidator/sequential.py
  odevalidator/validator.py
  sonar-project.properties
  tests/sequential_test.py
  tests/testfiles/good_bsmTx.json
  tests/validator_test.py
Labels: cleanup, testing

#25 Unit tests
  .travis.yml
  README.md
  odevalidator/validator.py
  setup.py
  tests/validator_field_test.py
  tests/validator_integration_test.py
  tests/validator_testcase_test.py
Labels: testing

#26 Fix variable naming code-smell
  odevalidator/sequential.py
Labels: cleanup
